#!/usr/bin/env bash

test $# -lt 1 && echo "Usage : $0 (version)" && exit 1
VERSION=$1

cd $(dirname "$(test -L "$0" && readlink -f "$0" || echo "$0")")
cd ../..

# Out dir
OUT="$(pwd)/src/$VERSION"

# Move to OpenResty dir
OPENRESTY="$(pwd)/build/openresty"
[ ! -d $OPENRESTY ] && "[Error] OpenResty dir does not exist: $OPENRESTY" && exit 1
cd $OPENRESTY || exit 1

# Check for package dir
PACKAGE="$(find openresty-* -maxdepth 0 -type d 2>/dev/null)"
[ -z "$PACKAGE" ] && echo "[Error] OpenResty package dir does not exist in dir: $(pwd)" && exit 1
PACKAGE="$(pwd)/$PACKAGE"

# Clean old dir
rm -fr "$OUT"
mkdir -p "$(dirname $OUT)"

# Move package
mv "$PACKAGE" "$OUT"

# Make configure executable
chmod +x "$OUT"/configure
