#!/usr/bin/env bash

test $# -lt 1 && echo "Usage : $0 (version)" && exit 1
VERSION=$1

cd $(dirname "$(test -L "$0" && readlink -f "$0" || echo "$0")")
cd ../..

# Out dir
OUT="$(pwd)/src/$VERSION"
PACKAGE="$(pwd)/build/openresty/openresty-1"

# Move package
mv "$OUT" "$PACKAGE" 
