#! /bin/bash

test $# -lt 1 && echo "Usage : $0 (version)" && exit 1
VERSION=$1

cd $(dirname "$(test -L "$0" && readlink -f "$0" || echo "$0")")
cd ../..

# Copy dirs
BUNDLER="$(pwd)/bundler"
COPY="$BUNDLER/copy"
COPY_ALL="$COPY/all"
COPY_VERSION="$COPY/version/$VERSION"
PATCHES="$BUNDLER/patches"

# Move to OpenResty dir
OPENRESTY="$(pwd)/build/openresty"
[ ! -d $OPENRESTY ] && "[Error] OpenResty dir does not exist: $OPENRESTY" && exit 1
cd $OPENRESTY || exit 1

# Check for package dir
PACKAGE="$(find openresty-* -maxdepth 0 -type d 2>/dev/null)"
[ -z "$PACKAGE" ] && echo "[Error] OpenResty package dir does not exist in dir: $(pwd)" && exit 1
PACKAGE="$(pwd)/$PACKAGE"

# Copy all files
for d in "$COPY_ALL" "$COPY_VERSION"; do
    find "$d/" -mindepth 1 -maxdepth 1 | xargs cp -r -t "$PACKAGE"
done


# Check for patches
BUNDLE="$PACKAGE/bundle"
cd "$BUNDLE"
libs="$(find -maxdepth 1 -type d | sed -r 's|^./||g')"

for lib in $libs; do
    cd "$PATCHES"
    patches="$(find -maxdepth 1 -name "$lib-*" | sed -r 's|^./||g')"
    
    # Apply patches
    for p in $patches; do
        echo "Applying patch: $p"
        
        patch="$PATCHES/$p"
        cd "$BUNDLE/$lib"
        patch -p1 < $patch
    done
done